export const ADDRESS_CHANGE = "ADDRESS_CHANGE";

export const SAVE_BUTTON_CLICKED = "SAVE_BUTTON_CLICKED";
export const UPDATE_BUTTON_CLICKED = "UPDATE_BUTTON_CLICKED";
export const EDIT_BUTTON_CLICKED = "EDIT_BUTTON_CLICKED";

export const ADD_NEW_BUTTON_CLICKED = "ADD_NEW_BUTTON_CLICKED";
export const ADD_NEW_CANCEL_BUTTON_CLICKED = "ADD_NEW_CANCEL_BUTTON_CLICKED";

export const UPDATE_CANCEL_BUTTON_CLICKED = "UPDATE_CANCEL_BUTTON_CLICKED";
