export const ADDRESS_CHANGE = "ADDRESS_CHANGE";

export const SAVE_BUTTON_CLICKED = "SAVE_BUTTON_CLICKED";
export const SAVE_ERROR = "SAVE_ERROR";
export const SAVE_SUCCESS = "SAVE_SUCCESS";

export const ADDRESS_NOT_FOUND_ERROR = "ADDRESS_NOT_FOUND_ERROR";

export const UPDATE_BUTTON_CLICKED = "UPDATE_BUTTON_CLICKED";
export const EDIT_BUTTON_CLICKED = "EDIT_BUTTON_CLICKED";
export const DELETE_BUTTON_CLICKED = "DELETE_BUTTON_CLICKED";

export const ADD_NEW_BUTTON_CLICKED = "ADD_NEW_BUTTON_CLICKED";
export const ADD_NEW_CANCEL_BUTTON_CLICKED = "ADD_NEW_CANCEL_BUTTON_CLICKED";

export const UPDATE_CANCEL_BUTTON_CLICKED = "UPDATE_CANCEL_BUTTON_CLICKED";
